#cloud-config

write_files:
- path: /tmp/docker-compose.yml
  owner: root:root
  permissions: '0644'
  encoding: b64
  content: dmVyc2lvbjogJzMnCgpzZXJ2aWNlczoKICB3ZzoKICAgIGltYWdlOiBkb2NrZXI1MTE0L2RvY2tlci1uZ2lueAogICAgcG9ydHM6CiAgICAgIC0gODA6ODAKICAgIGxvZ2dpbmc6CiAgICAgIGRyaXZlcjoganNvbi1maWxlCiAgICAgIG9wdGlvbnM6CiAgICAgICAgICBtYXgtc2l6ZTogNTBtCiAgICBlbnZpcm9ubWVudDoKICAgICAgLSBNQUlOVEVOQU5DRT10cnVlCiAgICAK

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose

runcmd:
  - cd /tmp && docker-compose up -d